default_stages: [commit, push]

repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
      -   id: detect-private-key
      -   id: check-merge-conflict
      -   id: check-json
      -   id: check-yaml

  - repo: https://github.com/psf/black
    rev: 21.6b0 # Replace by any tag/version: https://github.com/psf/black/tags
    hooks:
      - id: black

  -   repo: https://gitlab.com/pycqa/flake8
      rev: 3.9.2
      hooks:
      - id: flake8
        args: ['--config=setup.cfg', '--ignore=E203, W503, E741', '--max-line-length=300']
  
  -   repo: https://github.com/asottile/reorder_python_imports
      rev: v2.5.0
      hooks:
      -   id: reorder-python-imports